services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_auth
    expose:
      - 6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: docker/server.dockerfile    
    container_name: myapp
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=$(POSTGRES_URL)
    depends_on:
      - postgres
      - redis
      # - rabbitmq
    ports:
      - "8080:8080"
    restart: unless-stopped

  # worker:
  #   build: 
  #     context: .
  #     dockerfile: docker/server.dockerfile
  #   command: celery -A src.core.celery worker --loglevel=info
  #   depends_on:
  #     - rabbitmq
  #     - app
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

volumes:
  postgres_data:
  redis_data: